[package]
name = "onionusdp"
version = "0.1.0"
description = "OnionUSD-P: Payroll-enabled stablecoin built on SPL Token"
edition = "2021"
license = "MIT"
repository = "https://github.com/solana-program/token"

[lib]
crate-type = ["cdylib", "lib"]
name = "onionusdp"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
future-yield = []
default = []

[dependencies]
bytemuck = { version = "1.20.0", features = ["derive"] }
num-derive = "0.4"
num-traits = "0.2"
solana-account-info = "2.2.0"
solana-cpi = "2.2.0"
solana-decode-error = "2.2.0"
solana-instruction = "2.2.0"
solana-msg = "2.2.0"
solana-program = "2.2.0"
solana-program-entrypoint = "2.2.0"
solana-program-error = "2.2.0"
solana-program-memory = "2.2.0"
solana-program-pack = "2.2.0"
solana-pubkey = { version = "2.2.0", features = ["bytemuck"] }
solana-rent = "2.2.0"
solana-sdk-ids = "2.2.0"
solana-sysvar = { version = "2.2.0", features = ["bincode"] }
spl-token-interface = { path = "../../interface" }
thiserror = "2.0"

[dev-dependencies]
solana-program-test = "2.2.1"
solana-sdk = "2.2.1"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }